### ISSUE TITLE
Sprint brief

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/ds-pipe#13]
DS Pipe is an internal tool that helps the organization track how we are spending our time. It is not a detailed time-tracking tool. Instead, it provides an overall idea of:

1. where we are spending our time
2. whether we are budgeting well
3. what work we can take on in the near future

Time is tracked in egg-rollls, which are 4 hours of billable work. On average, an engineer or designer will have 16 eggrolls for a single sprint (2 weeks). Eggrolls (er) are tracked per person / project / phase / sprint:

```
{
  "id": 1,
  "project": 1,
  "phase": 1,
  "person": 7,
  "sprint": 11,
  "er": 2,
  "updated": "2017-07-10T20:00:00.000Z"
}
```

The project consists of:

- [Hapi API](https://github.com/developmentseed/ds-pipe-api)
- [React frontend](https://github.com/developmentseed/ds-pipe) App

## Goals of the sprint
We are about to release the first prototype of DS Pipe. The main feature that is lacking, is a way to edit eggrolls on the frontend. The API has endpoints to create, update and delete eggroll estimates, but there is no form for a human to do so.

### Day 1

1. @danielfdsilva will provide you with a rough scope for the new feature
2. set up development environment for frontend and API
3. come up with approach and confirm this with @danielfdsilva and @ricardomestre, ideally somewhere before or after lunch
4. implement
5. provide a quick end-of-day update, as if you were handing off your work to a colleague in the DC office

### Day 2

1. implement, checking in frequently with @danielfdsilva
2. end of day, set up a well documented PR with the final feature

If you don't manage to complete the feature fully, then make sure loose ends are wrapped up and that you provide a good write-up of what's missing.

@svanlaug

**Comment by olafveerman** [comment]
Pulling in the correct @svanza

**Comment by svanza** [comment]
Today I familiarized myself with Development Seed, how you do work here and the ds-pipe codebase.

1. I started a [branch](https://github.com/developmentseed/ds-pipe/tree/person-eggrolls-per-projectphase-table). 
2. I looked into how it's best to add functionality to the existing Table component, so that it can display dual information, i.e. to show project and phase.
3. Discussed with @danielfdsilva how it would be best to make the table show the additional information, we discussed conditional rendering based on a prop or if there were better scalable ways.
4. The conclusion was that the most optimal solution considering time would be to modify the sprintplan object in the person-page component before passing it as a prop to the table so that label is a combination of project and phase, i.e. Project/Phase. That way there is no need to change anything in the Table component itself.

Further work:
- [ Modify the sprintplan object in the person-page component to have a Project/Phase label]
- [ Make a local state in the person-page component that contains the sprint id of the sprint currently being shown in the table ]
- [ Update the state when arrow buttons are pressed, i.e. when you want to view a different sprint  ]
